<% num_zookeepers = 3 %>
<% deployment_name = "zookeeper-google-gce" %>
<% tld = "microbosh" %>
<% release_name = "zookeeper-boshrelease" %>
<% director_uuid = "CHANGE_ME" %>
---
<<<<<<< HEAD

compilation:
  cloud_properties:
     machine_type: n1-highcpu-2
  network: private
=======
compilation:
  cloud_properties:
     machine_type: n1-highcpu-2
  network: default
>>>>>>> 8d66518ac68cdd53070926d8e7f69bf28819c015
  reuse_compilation_vms: true
  workers: 6
name:  <%= deployment_name %>
director_uuid: <%= director_uuid %>

<<<<<<< HEAD
jobs:
  - name: zookeeper
    instances: <%= num_zookeepers %> 
=======
resource_pools:
  - name: vms
    network: default
    stemcell:
      name: bosh-google-kvm-ubuntu-trusty-go_agent
      version: 3153
    cloud_properties:
      machine_type: n1-standard-1
      root_disk_size_gb: 40
      root_disk_type: pd-standard

disk_pools:
  - name: disks
    disk_size: 32_768
    cloud_properties:
      type: pd-standard

networks:
  - name: default
    type: dynamic
    cloud_properties:
      network_name: default
      tags:
        - bosh

  - name: public
    type: vip


jobs:
  - name: zookeeper
    instances: <%= num_zookeepers %>
>>>>>>> 8d66518ac68cdd53070926d8e7f69bf28819c015

    templates:
      - name: zookeeper
        release: <%= release_name %>

    resource_pool: vms
<<<<<<< HEAD

    networks:
      - name: private
        type: dynamic
        cloud_properties:
          network_name: default
          tags:
            - zookeeper

    properties:
      zookeeper:
        servers:
          <% num_zookeepers.times do |i| %>
            <%= "- #{i}.zookeeper.private.#{deployment_name}.#{tld}\n" %>
          <% end %>
=======
    persistent_disk_pool: disks

    networks:
      - name: default
        default:
          - dns
          - gateway
      - name: public

    properties:
      zookeeper:
      servers:
        <% num_zookeepers.times do |i| %>
        <%= "- #{i}.zookeeper.default.#{deployment_name}.#{tld}\n" %>
        <% end %>
>>>>>>> 8d66518ac68cdd53070926d8e7f69bf28819c015

meta:
  environment: <%= deployment_name %>
  stemcell:
    name: bosh-google-kvm-ubuntu-trusty-go_agent
<<<<<<< HEAD
    version: latest

networks:
  - name: private
    type: dynamic
    cloud_properties:
      network_name: default
      ephemeral_external_ip: false
      ip_forwarding: false
      tags:
        - zookeeper
=======
    version: 3153
>>>>>>> 8d66518ac68cdd53070926d8e7f69bf28819c015

releases:
- name: <%= release_name %>
  version: latest

<<<<<<< HEAD
resource_pools:
  - name: vms
    network: private
    stemcell:
      name: bosh-google-kvm-ubuntu-trusty-go_agent
      version: latest
    cloud_properties:
      machine_type: g1-small
      root_disk_size_gb: 10
      root_disk_type: pd-standard

=======
>>>>>>> 8d66518ac68cdd53070926d8e7f69bf28819c015
update:
  canaries: 1
  canary_watch_time: 1000-30000
  max_in_flight: 50
  update_watch_time: 1000-30000
