<% num_zookeepers = 3 %>
<% deployment_name = "zookeeper-google-gce" %>
<% tld = "microbosh" %>
<% release_name = "zookeeper-boshrelease" %>
<% director_uuid = "CHANGE_ME" %>
---
director_uuid: <%= director_uuid %>

resource_pools:
  - name: vms
    network: private
    stemcell:
      name: bosh-google-kvm-ubuntu-trusty-go_agent
      version: 3153
    cloud_properties:
      machine_type: n1-standard-1
      root_disk_size_gb: 40
      root_disk_type: pd-standard

disk_pools:
  - name: disks
    disk_size: 32_768
    cloud_properties:
      type: pd-standard

networks:
  - name: private
    type: dynamic
    cloud_properties:
      network_name: default
      tags:
        - bosh

  - name: public
    type: vip


jobs:
  - name: zookeeper
    instances: <%= num_zookeepers %>

    templates:
      - name: nats
        release: latest

    resource_pool: vms
    persistent_disk_pool: disks

    networks:
      - name: private
        default:
          - dns
          - gateway
      - name: public

    properties:
      zookeeper:
      servers:
        <% num_zookeepers.times do |i| %>
        <%= "- #{i}.zookeeper.default.#{deployment_name}.#{tld}\n" %>
        <% end %>

meta:
  environment: <%= deployment_name %>
  stemcell:
    name: bosh-google-kvm-ubuntu-trusty-go_agent
    version: 3153

releases:
- name: <%= release_name %>
  version: latest

update:
  canaries: 1
  canary_watch_time: 1000-30000
  max_in_flight: 50
  update_watch_time: 1000-30000
